type iSynVMedicalIncidentsAll = {
  IncidentSeq: number;
  ID: number;
  ModifiedDate: Date | string | null;
  ModifiedBy: string | null;
  IncidentDate: Date | string | null;
  IncidentType: string;
  IncidentDescription: string | null;
  Diagnosis: string | null;
  Despatch: string | null;
  Comment: string | null;
  FollowUpFlag: boolean | null;
  FollowUp: string | null;
  FollowUpDate: Date | string | null;
  TimeIn: string;
  TimeOut: string;
  TreatedByDetails: string | null;
  InjuryDetails: string | null;
  ScaleOfInjuryCode: string;
  HowInjurySustained: string | null;
  InjuryActionTakenCode: string;
  InjuryMedicationSubscribedDetails: string | null;
  InjuryFollowUpDetails: string | null;
  InjuryReferrelCode: string;
  InjuryWitnessesDetails: string | null;
  NotificationSentWithStudentFlag: boolean;
  ParentPhonedNotificationFlag: boolean;
  ParentPhonedNotificationDetails: string | null;
  ParentMailedNotificationFlag: boolean;
  ParentMailedNotificationDetails: string | null;
  GuardianPhonedNotificationFlag: boolean;
  GuardianPhonedNotificationDetails: string | null;
  GuardianMailedNotificationFlag: boolean;
  GuardianMailedNotificationDetails: string | null;
  HeadOfHousePhonedNotificationFlag: boolean;
  HeadOfHousePhonedNotificationDetails: string | null;
  HeadOfHouseMailedNotificationFlag: boolean;
  HeadOfHouseMailedNotificationDetails: string | null;
  HeadOfHouseEMailedNotificationFlag: boolean;
  HeadOfHouseEMailedNotificationDetails: string | null;
  DirectorOfStudentsNotificationFlag: boolean;
  DirectorOfStudentsNotificationDetails: string | null;
  HeadOfSchoolNotificationFlag: boolean;
  HeadOfSchoolNotificationDetails: string | null;
  HeadmasterNotificationFlag: boolean;
  HeadmasterNotificationDetails: string | null;
  WorkcoverClaimSubmittedFlag: boolean;
  WorkcoverClaimSubmittedDetails: string | null;
  FollowupActionDetails: string | null;
  InjuryMedicationSubscribedDescription: string | null;
  VenueCode: string;
  RestrictedActivitiesSeq: number;
  RestrictedFlag: boolean | null;
  RestrictedDays: number | null;
  RestrictedEndDate: Date | string | null;
  ReviewDate: Date | string | null;
  Comments: string | null;
  RestrictedModifiedBy: number | null;
  RestrictedModifiedDate: Date | string | null;
  Type: string;
  StudentExtra: string | null;
  IncidentTypeDescription: string | null;
  Given1: string | null;
  Surname: string | null;
}

export default iSynVMedicalIncidentsAll
