import iVStudent from './iVStudent';
import iSynLuLearningPathway from '../Lookup/iSynLuLearningPathway';

type iSynStudentYear = {
  FileYear: number;
  ID: number;
  Status: string;
  StatusNextYear: string;
  StudentCampus: string;
  YearLevel: number;
  YearLevelSort: number;
  House: string;
  Form: string;
  Tutor: string;
  Boarder: string;
  Sports1: string;
  Sports2: string;
  LockerBook: string;
  LockerOther: string;
  FamilyPosition: number;
  LeavingDate: Date | string | null;
  ReturningDate: Date | string | null;
  LeavingReason: string;
  LeavingDestination: string;
  BoardingHouse: string;
  OverrideNextYearLevel: string;
  OverrideNextStudentCampus: string;
  OverrideNextBoarder: string;
  SchoolFTE: number;
  CalibreMark: number;
  TravelAllowanceFlag: boolean;
  SchoolingYearOffset: number;
  LeavingPostSchoolActivityCode: string;
  DestinationRegionCode: string;
  DestinationSchool1Code: string;
  DestinationSchool2Code: string;
  DestinationSchool3Code: string;
  DestinationSchool4Code: string;
  DestinationSchool5Code: string;
  DestinationSchool6Code: string;
  TeachingLearningNotesAcademicFlag: boolean;
  TeachingLearningNotesAttendanceFlag: boolean;
  TeachingLearningNotesBehaviouralFlag: boolean;
  TeachingLearningNotesCustodialFlag: boolean;
  TeachingLearningNotesHealthFlag: boolean;
  TeachingLearningNotesPersonalFlag: boolean;
  IBFlag: boolean;
  NCEALevel1: string;
  NCEALevel2: string;
  NCEALevel3: string;
  Level1LiteracyMet: string;
  Level1NumeracyMet: string;
  UELiteracyMet: string;
  UENumeracyMet: string;
  StudentYearsGUID: string;
  StudentYearsSeq: number;
  SIF3RefID: string;
  LearningPathway: string;

  SynVStudentAll?: iVStudent;
  SynLuLearningPathway?: iSynLuLearningPathway;
};

export default iSynStudentYear;
