type iSynStudentStatics = {
  ID: number;
  IntegrationFlag: boolean;
  SaleDailyCreditLimit: string;
  NewArrivalsProgramFlag: boolean;
  PriorOvernightCampsFlag: boolean;
  StudentTypeCode: string;
  ResourceLevelCode: string;
  SchoolZoneCode: string;
  InitialSchoolingDate: Date | string | null;
  FinanceAssistTypeCode: string;
  BenefitNumber: string;
  PaymentAmount: string;
  CandidateCount: number;
  ApplicationID: string;
  WithdrawnFlag: boolean;
  TertiaryReleaseFlag: boolean;
  ExportAddressOverrideFlag: boolean;
  ExportAddress1: string;
  ExportAddress2: string;
  ExportAddress3: string;
  ExportSuburb: string;
  ExportState: string;
  ExportCountryCode: string;
  ExportPostcode: string;
  EMAFlag: boolean;
  UserFlag1: boolean;
  UserFlag2: boolean;
  UserFlag3: boolean;
  UserFlag4: boolean;
  UserFlag5: boolean;
  MCEETYAFormReceivedDate: Date | string | null;
  ESLListeningLevelCode: string;
  ESLSpeakingLevelCode: string;
  ESLReadingLevelCode: string;
  ESLWritingLevelCode: string;
  TuitionWeeks: number;
  TertiaryAchievedFlag: boolean;
  AssistanceApproval: string;
  CommunityServiceFlag: boolean;
  PublishExamAnswerFlag: boolean;
  PublishCareerInformationFlag: boolean;
  PublishAwardsFlag: boolean;
  IntendedQualificationCode: string;
  ExchangeScheme: string;
  ReconfirmationFormReceivedDate: Date | string | null;
  AcceptableUseFormReceivedDate: Date | string | null;
  EnrolmentContractFlag: boolean;
  EligibilityCode: string;
  VerificationDocumentCode: string;
  SerialNumber: string;
  IntendedTertiaryCourseCode: string;
  CountryOfApplicationCode: string;
  EnquiryCampaignCode: string;
  StudiesCodeURL: string;
  GovernmentStudentNumber: string;
  WaiverEndDate: Date | string | null;
  AcademyFlag: boolean;
  VerificationDocumentExpiryDate: Date | string | null;
  OverrideEntryDate: Date | string | null;
  SecondaryTertiaryProgramme: string;
  CommunityServiceHours: string;
  YouthServicesSubmitContactDetailsFlag: boolean;
  EarlyLearningCode: string;
  VocationalEducationCode: string;
  IncludeInRollReturnFlag: boolean;
  STARFundedCourseDate: Date | string | null;
  FundingApplicationFlag: boolean;
  AdditionalLearningNeedsFlag: boolean;
};

export default iSynStudentStatics;
