import ServiceTestHelper from '../../helper/ServiceTestHelper';
import SynVFutureStudentService from '../../../services/Synergetic/SynVFutureStudentService';

describe('SynVFutureStudentService', () => {
  ServiceTestHelper.testCustom({
    name: 'getAll',
    serviceFn: SynVFutureStudentService.getAll,
    appMethod: 'get',
    callArgs: ServiceTestHelper.getCallArgs(),
    expectedArgs: ServiceTestHelper.getExpectedArgs("/syn/vFutureStudent"),
  });

  describe('mapFutureStudentToCurrent', () => {
    test('maps a future student into the current-student shape', () => {
      const mapped = SynVFutureStudentService.mapFutureStudentToCurrent(
        {
          FutureID: 10,
          FutureNameInternal: 'Student, Example',
          FutureNameExternal: 'Example Student',
          FutureLegalFullName: 'Example Student',
          FutureSurname: 'Student',
          FutureTitle: 'Ms',
          FutureInitials: 'ES',
          FutureSuffix: '',
          FuturePreferred: 'Example',
          FuturePreferredFormal: 'Example',
          FutureGiven1: 'Example',
          FutureGiven2: '',
          FutureOccupEmail: 'example@student.test',
          FutureBirthDate: '2010-01-01',
          FutureGender: 'F',
          FutureMobilePhone: '0400000000',
          FutureDefaultMobilePhone: '0400000000',
          FutureEmail: 'example@student.test',
          FutureEnrolYear: 2027,
          FutureStatus: 'ENROLLED',
          FutureStatusDescription: 'Enrolled',
          FutureStatusSynergyMeaning: 'Enrolled',
          FutureCampus: 'MAIN',
          FutureYearLevel: '7',
          FutureHouse: 'BLUE',
          FutureHouseDescription: 'Blue',
          FutureHeadOfHouse: '',
          FutureHouseCaptain: false,
          FutureForm: '7A',
          FutureBoarder: false,
          FutureBoarderType: '',
          FutureBoardingHouse: '',
          FutureEnrolDate: '2027-01-28',
          FuturePreviousSchoolCode: 'PS',
          FutureTuitionVariationType: 'LOCAL',
          FutureDoctorName: '',
          FutureDoctorPhone: '',
          FutureDoctorPhoneAlt: '',
          FutureDoctorAddress: '',
          FutureDoctorSpecialisation: '',
          FutureDoctor2Name: '',
          FutureDoctor2Phone: '',
          FutureDoctorPhone2Alt: '',
          FutureDoctor2Address: '',
          FutureDoctor2Specialisation: '',
          FutureDentistName: '',
          FutureDentistPhone: '',
          FutureDentistPhoneAlt: '',
          FutureDentistAddress: '',
          FutureDentist2Name: '',
          FutureDentist2Phone: '',
          FutureDentistPhone2Alt: '',
          FutureDentist2Address: '',
          FutureEmergencyName: '',
          FutureEmergencyAddress: '',
          FutureEmergencyPhone: '',
          FutureEmergencyPhoneAlt: '',
          FutureEmergencyRelat: '',
          FutureEmergency2Name: '',
          FutureEmergency2Address: '',
          FutureEmergency2Phone: '',
          FutureEmergency2PhoneAlt: '',
          FutureEmergency2Relat: '',
          FutureEmergency3Name: '',
          FutureEmergency3Address: '',
          FutureEmergency3Phone: '',
          FutureEmergency3PhoneAlt: '',
          FutureEmergency3Relat: '',
          FutureVisaType: '',
          FutureVisaIssuedDate: '',
          FutureVisaExpiryDate: '',
          FutureVisaNumber: '',
          FuturePassportCountryCode: '',
          FuturePassportExpiryDate: '',
          FuturePassportNo: '',
          FutureComment: '',
          FutureExternalStudentFlag: false,
          FutureEnglishSecondFlag: false,
          FutureDisabilityFlag: false,
          FutureFullFeeFlag: false,
          FutureIntendsTertiaryFlag: false,
          FutureStudentParishCode: '',
          FutureStudentParishDescript: '',
          ReligionCode: '',
          ReligionDescription: '',
          FuturePreviousSchoolDescription: '',
          FuturePreviousSchoolRSBNumber: '',
          FutureIndigenousFlag: false,
          FutureIBFlag: false,
          FutureApplicationDate: '2026-05-08',
          FutureMedicalAlertFlag: false,
          FutureSpecialNeedsFlag: false,
          FutureStudyAtHomeFlag: false,
          FutureTSIFlag: false,
          FutureESLProficiencyLevel: '',
          FutureESLListeningLevelCode: '',
          FutureESLSpeakingLevelCode: '',
          FutureESLReadingLevelCode: '',
          FutureESLWritingLevelCode: '',
          LegalPhotoWebFlag: false,
          LegalPhotoPromFlag: false,
          LegalPhotoPublicationFlag: false,
          FutureBarcode: '',
          FutureMedicalAlert: '',
          FutureNonResidentFlag: false,
          FutureBirthCertificateFlag: false,
          MCEETYAFormReceivedDate: '',
          FutureNationalityCode: '',
          FutureNationality2Code: '',
          FutureSubSchool: '',
          FutureAustudyFlag: false,
          FutureEmergencyRelatDescription: '',
          FutureEmergency2RelatDescription: '',
          FutureEmergency3RelatDescription: '',
          FutureAllowAutoChargesFlag: true,
          FutureSpecialBillingType: '',
          FutureTuitionNoSibFlag: false,
          LearningPathway: '',
          GenderSynergyMeaning: 'Female',
        } as any,
        {
          '7': {
            YearLevelSort: 7,
            Description: 'Year 7',
            YearLevelCoordinator: 'Coordinator',
            TimetableGroup: '7',
            IncludeInCensusFlag: true,
          } as any,
        }
      );

      expect(mapped.StudentID).toBe(10);
      expect(mapped.StudentYearLevelDescription).toBe('Year 7');
      expect(mapped.StudentYearLevelSort).toBe(7);
      expect(mapped.isFuture).toBe(true);
    });
  });
});
