type iSynVStudentAbsenceEvents = {
  AbsenceEventSeq: number;
  AbsenceEventsSeq?: number | null;
  AbsenceEventMasterAbsenceEventsSeq?: number | null;
  AbsenceEventTypeCode?: string | null;
  AbsenceEventTypeDescription?: string | null;
  AbsenceEventTypeSortSeq?: number | null;
  AbsenceEventTypeSynergyMeaning?: string | null;
  AbsenceEventTypeShortPrefix?: string | null;
  AbsenceEventTypeShortSuffix?: string | null;
  AbsenceEventDateTime?: string | Date | null;
  AbsenceEventDate?: string | Date | null;
  AbsenceEventTime?: string | null;
  AbsenceEventSchoolInOutStatus?: string | null;
  AbsenceEventComment?: string | null;
  AbsenceEventSystemGeneratedFlag?: boolean | null;
  AbsenceEventSystemProcessNumber?: number | null;
  AbsenceEventCreatedByID?: number | null;
  AbsenceEventCreatedDate?: string | Date | null;
  AbsenceEventModifiedByID?: number | null;
  AbsenceEventModifiedDate?: string | Date | null;
  AbsenceEventAbsenceTypeCode?: string | null;
  AbsenceEventAbsenceTypeDescription?: string | null;
  AbsenceEventAbsenceTypeSynergyMeaning?: string | null;
  AbsenceEventAbsenceTypeCountAsAbsenceFlag?: boolean | null;
  AbsenceEventAbsenceTypeExternalSystemType?: string | null;
  AbsenceEventAbsenceTypeExternalSystemCode?: string | null;
  AbsenceEventAbsenceTypeSortSeq?: number | null;
  AbsenceEventAbsenceReasonCode?: string | null;
  AbsenceEventAbsenceReasonDescription?: string | null;
  AbsenceEventEnteredInAdvanceFlag?: boolean | null;
  AbsenceEventNoteReceivedFlag?: boolean | null;
  AbsenceEventContactMadeFlag?: boolean | null;
  AbsenceEventContactReceivedFlag?: boolean | null;
  AbsenceEventApprovedFlag?: boolean | null;
  AbsenceEventReportedByID?: number | null;
  AbsenceEventReportedByIDName?: string | null;
  AbsenceEventReportedByName?: string | null;
  AbsenceEventsLeavingWithID?: number | null;
  AbsenceEventsLeavingWithIDName?: string | null;
  AbsenceEventPeriodCode?: string | null;
  AbsenceEventPeriodDescription?: string | null;
  AbsenceEventSortSeq?: number | null;
  AbsenceEventPeriodNumber?: number | null;
  AbsenceEventPeriodSynergyMeaning?: string | null;
  FileYear?: number | null;
  StudentID?: number | null;
  StudentSurname?: string | null;
  StudentGiven1?: string | null;
  StudentGiven2?: string | null;
  StudentPreferred?: string | null;
  StudentGender?: string | null;
  StudentBirthDate?: string | Date | null;
  StudentMailName?: string | null;
  StudentYearLevel?: string | null;
  StudentYearLevelSort?: string | null;
  StudentYearLevelDescription?: string | null;
  StudentYearLevelCoordinator?: string | null;
  YearLevelCoordinatorID?: number | null;
  StudentEntryDate?: string | Date | null;
  StudentLeavingDate?: string | Date | null;
  StudentFullFeeFlag?: boolean | null;
  StudentNonResidentFlag?: boolean | null;
  StudentAustudyFlag?: boolean | null;
  StudentEMAFlag?: boolean | null;
  StudentForm?: string | null;
  StudentFormDescription?: string | null;
  StudentFormHomeRoom?: string | null;
  StudentFormStaffName?: string | null;
  StudentFormStaffID?: number | null;
  StudentStatus?: string | null;
  StudentStatusDescription?: string | null;
  StudentStatusSynergyMeaning?: string | null;
  StudentCampus?: string | null;
  StudentCampusDescription?: string | null;
  StudentCampusHeadOfCampus?: string | null;
  StudentHouse?: string | null;
  StudentHouseDescription?: string | null;
  StudentHouseHeadOfHouse?: string | null;
  StudentHouseHeadOfHouseID?: number | null;
  StudentTutor?: string | null;
  StudentTutorDescription?: string | null;
  StudentTutorHomeRoom?: string | null;
  StudentTutorName?: string | null;
  StudentTutorID?: number | null;
  StudentBoarder?: string | null;
  StudentBoarderDescription?: string | null;
  StudentBoarderSynergyMeaning?: string | null;
  StudentBoardingHouse?: string | null;
  StudentFamilyPosition?: string | null;
  AbsenceEventNoteMadeFlag?: boolean | null;
  StudentSubSchool?: string | null;
  SubSchool?: string | null;
};

export default iSynVStudentAbsenceEvents;
