import iSynCommunity from './iSynCommunity';

type iPastStudent = {
  ID: number;
  CreatedDate: Date | string | null;
  CreatedBy: string | null;
  ModifiedDate: Date | string | null;
  ModifiedBy: string | null;
  Branch: string;
  LeftDate: Date | string | null;
  PeerYear: number;
  LastCampus: string;
  LastYearLevel: number;
  LastHouse: string;
  LastForm: string;
  EntryDate: Date | string | null;
  EntryCampus: string;
  EntryYearLevel: number;
  Boarder: number;
  KnownNames: string;
  AssocMember: string;
  AssocMemberNo: string;
  AssocInitialDate: Date | string | null;
  AssocExpiryDate: Date | string | null;
  Comment: string | null;
  LeavingReason: string;
  VisaType: string;
  VisaExpiryDate: Date | string | null;
  PassportNo: string;
  IBFlag: boolean;
  VisaNumber: string;
  PassportCountryCode: string;
  PassportExpiryDate: Date | string | null;
  BoardingHouse: string;
  IntendsTertiaryFlag: boolean;
  LeavingDestination: string;
  PassportIssuedDate: Date | string | null;
  VisaIssuedDate: Date | string | null;
  N16StuCode: string;
  N16ParCode: string;
  N16DebCode: string;
  AltCode: string;
  StudiesCode: string;
  TertiaryRegistrationCode: string;
  TimeTableCode: string;
  DebtorID: number;
  LearningPathway: string;
  SIF3RefID: string | null;
  SynCommunity?: iSynCommunity;
};

export default iPastStudent;
