type iSynVActivity = {
  ActivitySeq: number;
  ID: number;
  Activity: string;
  ActivityDescription: string;
  ActivityDate: Date;
  ActivityStatus: string;
  ActivityStatusDescription: string;
  ActivityByID: number;
  ActivityByPreferred: string | null;
  ActivityBySurname: string | null;
  ActivityByName: string | null;
  FollowUpFlag: boolean;
  FollowUpDate: Date | null;
  FollowUpID: number;
  FollowUpPreferred: string | null;
  FollowUpSurname: string | null;
  FollowUpName: string | null;
  Comment: string;
  MailRequestFlag: boolean;
  MailedDate: Date | null;
  MailedBy: string;
  ActivityCreatedBy: string;
  StudentType: string;
  StudentPreferred: string;
  StudentGiven1: string;
  StudentGiven2: string;
  StudentSurname: string;
  ContactID: number;
  ContactPreferred: string;
  ContactSurname: string;
  ContactMobile: string;
  ContactPhone: string;
  ContactAddress: string;
  ContactSpousePreferred: string;
  ContactSpouseSurname: string;
  MailedFlag: number;
};

export default iSynVActivity;
