type iSynSubjectClass = {
  FileType: string;
  FileYear: number;
  FileSemester: number;
  ClassCampus: string;
  ClassCode: string;
  Description: string;
  AssessmentCode: string;
  NormalYearLevel: number | null;
  NormalYearLevel2: number | null;
  LearningAreaCode: string;
  ClassID: string;
  FeeCode: string;
  FeeDefaultUnits: number;
  EventPayCode: string | null;
  EventActiveFlag: boolean;
  EventGroupFlag: boolean;
  BoardStudiesCode: string;
  CoreSubjectFlag: boolean;
  ResultsLockedFlag: boolean;
  CourseAutoSelectFlag: boolean;
  CopyToSem2ClassCode: string;
  AuthorBlockedFlag: boolean;
  TimetableImportKeepAssessFlag: boolean;
  TimetableImportNeverClearFlag: boolean;
  BoardStudiesType: string;
  AdjustmentMean: number;
  AdjustmentStandardDeviation: number;
  ClassType: string;
  Room: string;
  ReportingPeriodHours: number;
  SubjectClassesSeq: number;
  LocationCode: string;
  Comment: string | null;
  AssessmentSchemeApprovalNumber: string;
  LanguageCode: string;
  SubjectAssessmentsSeq: number | null;
  MultipleStaffMarkbookFlag: boolean;
  CommPortalMarkbookPublishFlag: boolean;
  SubjectClassesGUID: string;
  LinkedSubjectClassesSeq: number | null;
  SubjectClassCategoryCode: string  | null;
  MasterClassCode: string  | null;
  PortalElectiveDescription: string;
  AgeGroupCode: string  | null;
  ClassCodeNextSemester: string;
  SIF3RefID: string | null;
};

export default iSynSubjectClass;
